name: pouch
description: Generic Dart utilities and helper functions
version: 1.4.0
homepage: https://github.com/jesims/pouch

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  file: ^6.1.2
  glob: ^2.0.2
  intl: ^0.17.0
  path: ^1.8.1
  universal_io: ^2.0.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
  jesi_dart_analysis:
    git:
      url: https://github.com/jesims/jesi_dart_analysis.git
  faker: ^2.0.0
