version: 2.1
jobs:
  test-analyze-format-job:
    docker:
      - image: dart
    steps:
      - checkout
      - restore_cache:
          keys:
            - dart-{{ .Environment.CACHE_VERSION }}-{{ checksum "pubspec.yaml" }}
      - run: "dart pub get"
      - save_cache:
          key: dart-{{ .Environment.CACHE_VERSION }}-{{ checksum "pubspec.yaml" }}
          paths:
            - ~/.pub-cache
      - run: "dart analyze"
      - run: "dart format --set-exit-if-changed ."
      - run: "dart test"
workflows:
  main:
    jobs:
      - test-analyze-format-job
